ESERCIZI



#RIVISTA (CODR,NOMER,EDITORE)
#ARTICOLO (CODA,TITOLO,ARGOMENTO,CODR)

B)
#TROVARE IL CODICE E IL NOME DELLE RIVISTE 
#CHE NON HANNO MAI PUBBLICATO 
#ARTICOLI DI MOTOCICLISMO

SELECT CODR, NOMER
FROM RIVISTA
WHERE CODR NOT IN    (SELECT CODR 
                    FROM ARTICOLO
                    WHERE ARGOMENTO = "MOTOCICLISMO")



C)
#TROVARE IL CODICE E IL NOME DELLE RIVISTE CHE HANNO PUBBLICATO
#SOLO ARTICOLI DI MOTOCICLISMO

SELECT CODR, NOMER
FROM RIVISTA
WHERE CODR NOT IN (SELECT CODR 
                  FROM ARTICOLO
                  WHERE ARGOMENTO <>"MOTOCICLISMO");


D)
#TROVARE IL CODICE E IL NOME DELLE RIVISTE CHE HANNO PUBBLICATO
#ARTICOLI DI MOTOCICLISMO O AUTO 

SELECT CODR NOMER
FROM RIVISTA
WHERE CODR IN (SELECT CODR
                FROM ARTICOLO
                WHERE ARGOMENTO = "MOTOCICLISMO"
                OR ARGOMENTO= 'AUTO');

E)
#TROVARE IL CODICE E IL NOME DELLE RIVISTE CHE PUBBLICANO
#ARTICOLI SIA DI MOTOCICLISMO SIA DI AUTO 

SELECT CODR, NOME
FROM RIVISTA 
WHERE CODR IN (SELECT CODR 
                FROM ARTICOLO
                WHERE ARGOMENTO = 'MOTOCICLISMO')
       AND CODR IN (SELECT CODR
                    FROM ARTICOLO
                    WHERE ARGOMENTO = 'AUTO');



F)
#TROVARE IL CODICE E IL NOME DELLE RIVISTE CHE HANNO PUBBLICATO
#ALMENO 2 ARTICOLI DI MOTOCICLISMO

SELECT CODR, NOMER
FROM ARTICOLO
WHERE CODR IN (SELECT CODR
                FROM ARTICOLO
                WHERE ARGOMENTO = 'MOTOCICLISMO'
                GROUP BY CODR 
                HAVING COUNT(*)>=2);


G)
#TROVARE IL CODICE E IL NOME DELLE RIVISTE CHE HANNO PUBBLICATO
#UN SOLO ARTICOLO DI MOTOCICLISMO

SELECT CODR, NOMER
FROM ARTICOLO
WHERE CODR IN (SELECT CODR 
              FROM ARTICOLO
              WHERE ARGOMENTO = 'MOTOCICLISMO'
              GROUP BY CODR 
              HAVING COUNT(*)=1);






